### ISSUE TITLE
Support for armv6 and armv7 architectures

### ISSUE THREAD

**Issue by joeldhenry** [vlrpi/rpi-teamcity-server#1]
Any setup configuration or recommended settings? my RPI3 just freezes after I start the setup process on localhost:8111 :(

**Comment by vova-lantsov-dev** [comment]
Can you please share your docker configuration used to start my image?

**Comment by vova-lantsov-dev** [comment]
Here is how I run it: https://github.com/vova-lantsov-dev/rpi-teamcity-dotnet/blob/master/docker-compose.yml

To start containers: `docker-compose up -d`
To stop them: `docker-compose down`

**Comment by joeldhenry** [comment]
i just used the docker-ce default and did `docker run -p 8111:8111 -d vlrpi/rpi-teamcity-server`

**Comment by joeldhenry** [comment]
thanks for the reply! yes i followed your steps with latest docker, composer, LTS linux. what database type are you using? i think it might be failing during database setup

**Comment by vova-lantsov-dev** [comment]
Unfortunately I didn't setup an external database yet, my TeamCity instance is working with internal db at the moment. I'm planning to transfer to PostgreSQL, but later. Anyway, database shouldn't be a problem. Try to read docker logs to figure out what's going on.

**Comment by joeldhenry** [comment]
yea im just using an internal DB too. during the setup it just gets too 36% and freezes and SSH and the website become completely unresponsive.

**Comment by vova-lantsov-dev** [comment]
I just checked the architecture of RPi 3 and found that it's 32 bit armv7l CPU (support for 64 bit arm comes with armv8). So I might try to publish armv7 and armv6 images as well, and you can try if it works

**Comment by vova-lantsov-dev** [comment]
https://stackoverflow.com/a/37793795

**Comment by vova-lantsov-dev** [comment]
@joeldhenry build is in progress, you can track it here: https://tc.vova-lantsov.dev/project.html?projectId=VlRpi_VlRpiBuild&tab=projectOverview (Login as guest)

As soon as it's finished, you will need to force pull the images from Docker Hub. After that you will get the image with architecture that your Raspberry Pi needs - arm/v6 or arm/v7.

**Comment by vova-lantsov-dev** [comment]
Please let me know if it doesn't help

**Comment by vova-lantsov-dev** [comment]
Closing this, feel free to create a new issue if needed.

**Comment by joeldhenry** [comment]
Thanks! Your instance is so fast!! Linux LTS 64bit is still unusable on my rpi 3 :(

**Comment by vova-lantsov-dev** [comment]
Hi @joeldhenry , just want to let you know that I'm building a next version of images https://hub.docker.com/u/vlrpi
They are now using the different base images for better performance on non-ARM64 architectures. Before I used the same ARM64 images for both ARM32 and ARM64.
I will be glad if you can test my new images on RPi 3
